### ISSUE TITLE
Error when importing the module

### ISSUE THREAD

**Issue by noush225** [leewinder/ng2-dynamic-dialog#11]
Hello guys!
When i try to import the module i have this error : 

`ERROR in .../node_modules/ng2-dynamic-dialog/background/background.component.ts (11,15): Cannot find name '__filename'.

ERROR in .../node_modules/ng2-dynamic-dialog/dialog/dialog.component.ts (17,15): Cannot find name '__filename'.`

Any ideas? I'm new to Angular development so i don't know what to do

**Comment by dawg6** [comment]
Having the same issue. Anyone have any clue? Tried googling, but can't seem to find a similar problem anywhere else.

Edit: I made a copy of the module and removed the "moduleId: __filename" lines from the *.component.ts files and it now works fine for me.

**Comment by leewinder** [comment]
Resolved in v5.0.0, just make sure you've included the @types dependencies
https://github.com/leewinder/ng2-dynamic-dialog/blob/develop/samples/package.json#L48
