### ISSUE TITLE
Can't import module

### ISSUE THREAD

**Issue by krzysztof-miemiec** [leewinder/ng2-dynamic-dialog#2]
after adding Ng2DynamicDialogModule to imports array of my NgModule and compiling using webpack I get this runtime error:
`Uncaught Error: Unexpected value 'DialogModule' imported by the module 'AppModule'`

I use Angular 2.1.2, Webpack 1.13.3

**Comment by DeyuanTan** [comment]
+1

**Comment by leewinder** [comment]
Should be resolved in 2.1.0 due to the removal of module.id
https://github.com/leewinder/ng2-dynamic-dialog/pull/9
