### ISSUE TITLE
Calling function 'makeDecorator', function calls are not supported

### ISSUE THREAD

**Issue by st-clair-clarke** [leewinder/ng2-dynamic-dialog#3]
Hi, 
I am trying to use ng2-dynamic-dialog. All packages are correctly loaded. However when I attempt to use the module I get the following

`ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in J:/workspace/angular2/ts/epimss/node_modules/ng2-dynamic-dialog/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in J:/workspace/angular2/ts/epimss/node_modules/ng2-dynamic-dialog/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in J:/workspace/angular2/ts/epimss/node_modules/ng2-dynamic-dialog
/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in J:/workspace/angular2/ts/epimss/node_modules/ng2-dynamic-dialog/node_modules/@angular/core/index.d.ts, resolving symbol DialogModule in J:/workspace/angular2/ts/epimss/node_modules/ng2-dynamic-dialog/module/dialog.module.ts, resolving symbol DialogModule in J:/workspace/angular2/ts/epimss/node_modules/ng2-dynamic-dialog/module/dialog.module.ts`

Could this be due to the changes in current angular2.x.y where x is > 0?

Thanks

**Comment by amit-vohra** [comment]
We are facing exact same issue. Any help appreciated.

**Comment by mlk5060** [comment]
Same here!

**Comment by leewinder** [comment]
I think this is the same issue present in ng2-file-drop, so I'll make the same changes here and release a new package
https://github.com/leewinder/ng2-file-drop/issues/8

**Comment by leewinder** [comment]
Added the use of peerDependancies alongside dependancies in the npm package which should resolve this
https://github.com/leewinder/ng2-dynamic-dialog/pull/9
