### ISSUE TITLE
Comptibility with angular 4

### ISSUE THREAD

**Issue by st-clair-clarke** [leewinder/ng2-dynamic-dialog#4]
Hi,
Is ng2-dynamic-dialog comptible with angular 4? I cannot get it to run with this version.
Thanks

**Comment by Farang1969** [comment]
I get the same problem here, but it seems to be a problem with tslerp.

**Comment by leewinder** [comment]
Upgraded to Angular ^4.1.3 and the latest build of tsLerp
https://github.com/leewinder/ng2-dynamic-dialog/pull/9
