### ISSUE TITLE
Module parse failed: for Webpack and Angular4

### ISSUE THREAD

**Issue by khaled-ansary** [leewinder/ng2-dynamic-dialog#5]
Hi, I am getting an error to run it with Webpack and Angular4

ERROR in ./~/ng2-dynamic-dialog/styles/behaviour.ts
Module parse failed: F:\git project\mitreId-client\node_modules\ng2-dynamic-dial                                                          og\styles\behaviour.ts Unexpected token (8:25)
You may need an appropriate loader to handle this file type.

     // Show the dialog close when the user clicks outside
    exitOnOffDialogClick = true;

|    // Transitions
 @ ./~/ng2-dynamic-dialog/index.ts 5:0-76

**Comment by leewinder** [comment]
This should be fixed as part of the 2.1.0 release
https://github.com/leewinder/ng2-dynamic-dialog/pull/9

Upgraded to Angular ^4.1.3 and removed the use of module.id
